host:
  http_port: '8080'
  cover_cache:
    directory: ./.pmomusic_covers
    size: 2000
  audio_cache:
    directory: ./.pmomusic_audio
    size: 500
  logger:
    buffer_capacity: 200
    enable_console: true
    min_level: INFO
  mediarenderer:
    mpd_renderer: null
  mediaserver:
    qobuz:
      udn: uuid:28963b75-4c5f-4da7-b10e-ffafd
accounts:
  qobuz:
    username: eric@coissac.eu
    password: '*Misfcr73110$'
devices:
  mediarenderer:
    pmo_mediarenderer:
      udn: 15a13316-daac-47f0-b64e-47e56f5e3b51
  mediaserver:
    pmo_mediaserver:
      udn: 23df0bfa-cfef-4724-b731-00f66fadf176
