host:
  http_port: '8080'
  cover_cache:
    directory: ./.pmomusic_covers
    size: 2000
  audio_cache:
    directory: ./.pmomusic_audio
    size: 500
  logger:
    buffer_capacity: 200
    enable_console: true
    min_level: INFO
devices:
  mediarenderer:
    mpd_renderer: null
    fakerenderer:
      udn: d7eaad15-7d21-4411-926a-bc1eea0713db
    mediarenderer:
      udn: f9ef6c21-0ed3-470c-9846-bc1ae85fea62
  mediaserver:
    qobuz:
      udn: 28963b75-4c5f-4da7-b10e-ffafd
accounts:
  qobuz:
    username: eric@coissac.eu
    password: '*Misfcr73110$'
