use crate::define_service;

pub mod variables;
pub mod actions;

use actions::{
    GETDEVICECAPABILITIES, GETMEDIAINFO, GETPOSITIONINFO, GETTRANSPORTINFO,
    GETTRANSPORTSETTINGS, NEXT, PAUSE, PLAY, PREVIOUS, SEEK,
    SETNEXTAVTRANSPORTURI, SETAVTRANSPORTURI, STOP
};
use variables::{
    ABSOLUTETIMEPOSITION, AVTRANSPORTNEXTURI, AVTRANSPORTNEXTURIMETADATA,
    AVTRANSPORTURI, AVTRANSPORTURIMETADATA, A_ARG_TYPE_INSTANCE_ID,
    A_ARG_TYPE_PLAY_SPEED, A_ARG_TYPE_SEEKMODE, CURRENTTRACK,
    CURRENTTRACKDURATION, NUMBEROFTRACKS, RELATIVETIMEPOSITION, SEEKMODE,
    TRANSPORTPLAYSPEED, TRANSPORTSTATE, TRANSPORTSTATUS
};

define_service! {
    pub static AVTTRANSPORT = "AVTransport" {
        variables: [
            ABSOLUTETIMEPOSITION,
            A_ARG_TYPE_INSTANCE_ID,
            A_ARG_TYPE_PLAY_SPEED,
            A_ARG_TYPE_SEEKMODE,
            AVTRANSPORTNEXTURI,
            AVTRANSPORTNEXTURIMETADATA,
            AVTRANSPORTURI,
            AVTRANSPORTURIMETADATA,
            CURRENTTRACK,
            CURRENTTRACKDURATION,
            NUMBEROFTRACKS,
            RELATIVETIMEPOSITION,
            SEEKMODE,
            TRANSPORTPLAYSPEED,
            TRANSPORTSTATE,
            TRANSPORTSTATUS,
        ],
        actions: [
            GETDEVICECAPABILITIES,
            GETMEDIAINFO,
            GETPOSITIONINFO,
            GETTRANSPORTINFO,
            GETTRANSPORTSETTINGS,
            NEXT,
            PAUSE,
            PLAY,
            PREVIOUS,
            SEEK,
            SETNEXTAVTRANSPORTURI,
            SETAVTRANSPORTURI,
            STOP,
        ]
    }
}